print(len("casa"))
print(max(5,18,55,100))
print(min(2,5,9,))
print(list(range(20) ))
print(round(3.45))
print(sum([1,2,3]))
print(type(7.5))
expressao = input("digite a operacao matematica que deseja executar: ")
eval(f"print({expressao})")